/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Entries {
  article: string | null;
  body_html: string;
  gender: string | null;
  headword: string;
  homonym_num: number | null;
  id: Generated<number | null>;
  inflections: string | null;
  pos: string | null;
}

export interface EntriesFts {
  headword: string | null;
  inflections: string | null;
}

export interface Phrases {
  body_html: string;
  dutch: string;
  entry_id: number;
  id: Generated<number | null>;
  translation: string;
}

export interface PhrasesFts {
  dutch: string | null;
}

export interface DB {
  entries: Entries;
  entries_fts: EntriesFts;
  phrases: Phrases;
  phrases_fts: PhrasesFts;
}
